version: "3.8"

services:
  # Database Service (PostgreSQL)
  db:
    image: postgres:15
    container_name: market_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Airflow Service
  airflow:
    image: apache/airflow:2.7.1-python3.10
    container_name: market_airflow
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/plugins/src
    ports:
      - "8080:8080"
    command: standalone
    depends_on:
      - db

volumes:
  postgres_data:
